services:
  client:
    container_name: client
    build: "./client"
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    environment:
      - PUBLIC_KEY=$PUBLIC_KEY
      - SERVER=$SERVER
      - SERVER_KEY_PATH=$SERVER_KEY_PATH
      - SERVER_CERT_PATH=$SERVER_CERT_PATH
    volumes:
      - $PATH_TO_SSL:/app/ssl
  server:
    container_name: server
    build: "./server"
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    volumes:
      - database:/tmp/
    environment:
      - PRIVATE_KEY=$PRIVATE_KEY
      - CONNECTION_STRING=$CONNECTION_STRING
      - CLIENT=$CLIENT
      - SENDGRID_API_KEY=$SENDGRID_API_KEY
volumes:
  database:
    external: true